# Generated by Django 6.0.6 on 2026-06-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell others about yourself, your interests, etc.', max_length=500)),
                ('department', models.CharField(blank=True, help_text='e.g. Computer Science, Mechanical Engineering', max_length=100)),
                ('contact_info', models.CharField(blank=True, help_text='e.g. email@example.com, phone number, Discord tag', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Python, Photoshop, Guitar, Spanish', max_length=100)),
                ('description', models.TextField(help_text='Provide details about what you want to teach or learn.')),
                ('category', models.CharField(choices=[('Programming', 'Programming & Tech'), ('Design', 'Design & Creative'), ('Music', 'Music & Arts'), ('Languages', 'Languages'), ('Academics', 'Academics & Tutoring'), ('Fitness', 'Fitness & Sports'), ('Others', 'Others')], default='Programming', max_length=50)),
                ('skill_type', models.CharField(choices=[('TEACH', 'Teach (I can teach this skill)'), ('LEARN', 'Learn (I want to learn this skill)')], default='TEACH', max_length=10)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Introduce yourself and propose a schedule or exchange details.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='portal.skill')),
            ],
        ),
    ]
